server {
    listen 80;
    listen [::]:80;
    server_name huggy.BUNNYURL;

    root /var/www/bunnysites/hugo-example/public;
    index index.html;

    access_log /var/log/nginx/huggy.BUNNYURL.access.log;
    error_log  /var/log/nginx/huggy.BUNNYURL.error.log warn;

    location / {
        try_files $uri $uri/ =404;
    }
}
